#!/usr/bin/env bash

# 01_Download data:



# 02_Quality control of raw sequences:
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=1000M


# remove 'junk'-transcripts:
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=8000M
